### ISSUE TITLE
Ballyhoo Golf

### ISSUE THREAD

**Issue by derekober** [hhgr/Ballyhoo#1]
Adam,

The Golf page is filed as an "Event Category" while the rest of the sports are listed as a sport...the Golf page (although you and I both filled out info for it) has the page listing a blank page of events instead of that info. Did I mess something up in my editing?!

**Comment by AdamChlan** [comment]
Yes, it looks like you selected the menu item from the “events categories” box, when you should have picked it from the “sports” options. Let me know if you need help.

**Comment by MelissaHall** [comment]
I don't think we have a sports option on there - see screen shot 
![ballyhoo screen shot](https://cloud.githubusercontent.com/assets/15017550/10495587/a61e822a-728a-11e5-96f4-60221680e066.png)

**Comment by AdamChlan** [comment]
Click the “Screen Options” tab up top, and see if you can activate it there.

**Comment by MelissaHall** [comment]
That worked - Thanks!

**Comment by AdamChlan** [comment]
:thumbsup:
