### ISSUE TITLE
Recruitment Tab/ Page on Ballyhoo

### ISSUE THREAD

**Issue by MelissaHall** [hhgr/Ballyhoo#2]
Adam - We need to add a recruitment tab and page/pages on the Ballyhoo site - Can you help by adding that to the site? Can you get this added by EOD Wednesday?

The first info that needs to be on there is info re our recruiting seminar - See below:

Ballyhoo Sports Academy Presents:

NCAA Recruiting Seminar

Sunday, January 31 – 6PM

The Terrace at Heritage Hills Resort
 
<reg link> https://tms.ezfacility.com/OnlineRegistrations/Register.aspx?CompanyID=3379&GroupID=1471299 
Ballyhoo Athletes/Parents - Free (present Key tag)

Non Ballyhoo Athletes - $25 (Pay at the Door or present online payment receipt)

Parents and athletes are invited to attend Ballyhoo’s NCAA Recruiting Seminar to learn the ins-and-outs of the NCAA recruitment process.  Geared towards High School Sophomores and Juniors the seminar will cover topics including:

NCAA Eligibility
Test Scores
What Coaches Are Looking For
Athlete Recruiting Checklist
DI vs DII vs DIII
And More
 
Guest speakers at the event include:

Ashton Bankos – D3 Athlete; College Recruiter; Ballyhoo Sports Academy Coach
Matt Marshall – D2 Athlete; Ballyhoo Sports Academy Sports Performance Director
Andrew Hirsch – D3 Athlete; Gettysburg Baseball Assistant Coach & Recruiter; Baseball Factory Coach
Jason Aspito – D1 Athlete; Professional Baseball Player; Ballyhoo Sports Academy Baseball Director

**Comment by AdamChlan** [comment]
Sure, no problem.
